"""Parse the resolved-by-repo and resolved-by-year tables.

The official sb-cli submission README contains markdown blocks summarising
``resolved/total`` per repository and per issue year. This script parses
those blocks and emits machine- and LaTeX-readable copies.
"""

from __future__ import annotations

import json
import re

from _paths import STATS_DIR, SUBMISSION_README


_BLOCK_REPO = re.compile(r"Resolved by Repository\s*\n(.*?)\n=+", re.DOTALL)
_BLOCK_YEAR = re.compile(r"Resolved by Time\s*\n(.*?)\n=+", re.DOTALL)
_LINE_REPO = re.compile(r"-\s+([\w./-]+):\s+(\d+)/(\d+)")
_LINE_YEAR = re.compile(r"-\s+(\d{4}):\s+(\d+)/(\d+)")


def parse_block(text: str, block: re.Pattern, line: re.Pattern) -> list[dict]:
    rows: list[dict] = []
    m = block.search(text)
    if not m:
        return rows
    for ln in line.finditer(m.group(1)):
        key, resolved, total = ln.group(1), int(ln.group(2)), int(ln.group(3))
        rate = resolved / total if total else 0.0
        rows.append(
            {"key": key, "resolved": resolved, "total": total, "rate": round(rate, 4)}
        )
    return rows


def emit_tex(name: str, rows: list[dict]) -> str:
    lines = [
        f"% Auto-generated by compute_repo_year_breakdown.py: {name}",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        f"{name} & Resolved & Total & Rate \\\\",
        r"\midrule",
    ]
    total_r = sum(r["resolved"] for r in rows)
    total_t = sum(r["total"] for r in rows)
    for r in rows:
        key_tex = r["key"].replace("_", r"\_")
        lines.append(
            f"{key_tex} & {r['resolved']} & {r['total']} & {r['rate'] * 100:.1f}\\% \\\\"
        )
    if rows:
        lines.append(r"\midrule")
        rate = total_r / total_t if total_t else 0.0
        lines.append(
            f"\\textbf{{Total}} & \\textbf{{{total_r}}} & \\textbf{{{total_t}}} & "
            f"\\textbf{{{rate * 100:.1f}\\%}} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def emit_split_tex(name: str, rows: list[dict]) -> str:
    total_r = sum(r["resolved"] for r in rows)
    total_t = sum(r["total"] for r in rows)
    table_rows = [
        {
            "key": r["key"].replace("_", r"\_"),
            "resolved_total": f"{r['resolved']}/{r['total']}",
            "rate": f"{r['rate'] * 100:.1f}\\%",
        }
        for r in rows
    ]

    split_at = (len(table_rows) + 1) // 2
    left_rows = table_rows[:split_at]
    right_rows = table_rows[split_at:]
    empty = {"key": "", "resolved_total": "", "rate": ""}

    lines = [
        f"% Auto-generated by compute_repo_year_breakdown.py: {name}",
        r"\resizebox{\columnwidth}{!}{%",
        r"\begin{tabular}{@{}lrr||lrr@{}}",
        r"\toprule",
        f"{name} & Resolved/Total & Rate & {name} & Resolved/Total & Rate \\\\",
        r"\midrule",
    ]
    for left, right in zip(left_rows, right_rows + [empty] * len(left_rows)):
        lines.append(
            f"{left['key']} & {left['resolved_total']} & {left['rate']} & "
            f"{right['key']} & {right['resolved_total']} & {right['rate']} \\\\"
        )
    if rows:
        rate = total_r / total_t if total_t else 0.0
        lines.append(r"\midrule")
        lines.append(
            f"\\multicolumn{{6}}{{c}}{{\\textbf{{Overall: {total_r}/{total_t} "
            f"({rate * 100:.1f}\\%)}}}} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}%")
    lines.append(r"}")
    return "\n".join(lines) + "\n"


def main() -> None:
    STATS_DIR.mkdir(parents=True, exist_ok=True)
    text = SUBMISSION_README.read_text()
    repo_rows = parse_block(text, _BLOCK_REPO, _LINE_REPO)
    year_rows = parse_block(text, _BLOCK_YEAR, _LINE_YEAR)

    (STATS_DIR / "resolved_by_repo.json").write_text(
        json.dumps({"rows": repo_rows}, indent=2)
    )
    (STATS_DIR / "resolved_by_year.json").write_text(
        json.dumps({"rows": year_rows}, indent=2)
    )
    (STATS_DIR / "resolved_by_repo.tex").write_text(
        emit_split_tex("Repository", repo_rows)
    )
    (STATS_DIR / "resolved_by_year.tex").write_text(emit_tex("Year", year_rows))
    print(json.dumps({"repos": len(repo_rows), "years": len(year_rows)}, indent=2))


if __name__ == "__main__":
    main()
