"""Per-run pass@1 statistics for the eight Orchestra runs.

Reads each run's ``report.json`` (the standard ``mini-swe-agent``
report format) under the trajectory bundle and writes:

* ``per_run_pass1.json``: machine-readable summary with per-run counts
  and aggregate min/max/mean/stdev.
* ``per_run_pass1.csv``: same data in CSV form.
* ``per_run_pass1.tex``: LaTeX ``tabular`` fragment ready to be
  ``\\input{}``-ed by the manuscript.

If the Java xcheck summary is present, the table also includes the
available Java per-source-run contribution after xcheck selection. The
Java bundle does not ship per-leg per-instance eval reports, so these
columns are labelled as selector-attributed counts rather than pass@1.
"""

from __future__ import annotations

import csv
import json
import statistics

from _paths import JAVA_XCHECK_PREDS_SCORE, STATS_DIR, TRAJ_RUNS_DIR


def main() -> None:
    STATS_DIR.mkdir(parents=True, exist_ok=True)
    runs = sorted(p for p in TRAJ_RUNS_DIR.iterdir() if p.is_dir())

    rows = []
    resolved_counts: list[int] = []
    for run_dir in runs:
        report_path = run_dir / "report.json"
        if not report_path.exists():
            continue
        report = json.loads(report_path.read_text())
        rows.append(
            {
                "run": run_dir.name,
                "total_instances": report.get("total_instances"),
                "submitted_instances": report.get("submitted_instances"),
                "completed_instances": report.get("completed_instances"),
                "resolved_instances": report.get("resolved_instances"),
                "unresolved_instances": report.get("unresolved_instances"),
                "empty_patch_instances": report.get("empty_patch_instances"),
                "error_instances": report.get("error_instances"),
            }
        )
        resolved_counts.append(int(report.get("resolved_instances", 0)))

    java_rows = load_java_rows()
    summary = {
        "runs": rows,
        "java_source_runs": java_rows,
        "n_runs": len(rows),
        "min_resolved": min(resolved_counts) if resolved_counts else None,
        "max_resolved": max(resolved_counts) if resolved_counts else None,
        "mean_resolved": (
            round(statistics.mean(resolved_counts), 4) if resolved_counts else None
        ),
        "stdev_resolved_population": (
            round(statistics.pstdev(resolved_counts), 4)
            if len(resolved_counts) > 1
            else None
        ),
    }
    if java_rows:
        java_resolved = [int(row["resolved_count"]) for row in java_rows]
        java_selected = [int(row["selected_count"]) for row in java_rows]
        summary.update(
            {
                "java_mean_selected": round(statistics.mean(java_selected), 4),
                "java_mean_resolved": round(statistics.mean(java_resolved), 4),
                "java_stdev_resolved_population": round(
                    statistics.pstdev(java_resolved), 4
                ),
            }
        )

    (STATS_DIR / "per_run_pass1.json").write_text(json.dumps(summary, indent=2))

    with (STATS_DIR / "per_run_pass1.csv").open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "leg",
                "python_run",
                "python_resolved",
                "python_unresolved",
                "python_empty_patch",
                "python_error",
                "python_total",
                "python_rate",
                "java_run",
                "java_selected",
                "java_resolved_selected",
                "java_unresolved_selected",
                "java_conditional_rate",
            ]
        )
        for idx, r in enumerate(rows):
            total = r["total_instances"] or 1
            rate = (r["resolved_instances"] or 0) / total
            java = java_rows[idx] if idx < len(java_rows) else {}
            java_selected = int(java.get("selected_count", 0) or 0)
            java_resolved = int(java.get("resolved_count", 0) or 0)
            java_rate = java_resolved / java_selected if java_selected else 0.0
            writer.writerow(
                [
                    idx + 1,
                    r["run"],
                    r["resolved_instances"],
                    r["unresolved_instances"],
                    r["empty_patch_instances"],
                    r["error_instances"],
                    r["total_instances"],
                    f"{rate:.4f}",
                    java.get("run_dir_name", ""),
                    java_selected or "",
                    java_resolved or "",
                    java.get("unresolved_count", ""),
                    f"{java_rate:.4f}" if java_selected else "",
                ]
            )

    lines = [
        "% Auto-generated by paper/final/sources/paper-src-test-prompt/compute_per_run_stats.py",
        "% Python columns: trajectories/q35_verified500_tts8_75p2_submission_bundle_20260326-055715_merged500/runs/r0X_s100X/report.json",
        "% Java columns: experiments/java/kozuchi-mswe-java-20260429/logs/_harness/xcheck_preds_score.json source_runs[]",
        "% Note: Java per-leg pass@1 reports are not shipped; Java columns are xcheck-selected source-run contributions.",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"Run & Python pass@1 & \multicolumn{2}{c@{}}{Java xcheck-selected} \\",
        r"\cmidrule(lr){2-2}\cmidrule(l){3-4}",
        r" & Resolved & Selected & Resolved \\",
        r"\midrule",
    ]
    for idx, r in enumerate(rows):
        total = r["total_instances"] or 1
        rate = (r["resolved_instances"] or 0) / total * 100.0
        java = java_rows[idx] if idx < len(java_rows) else {}
        java_selected = int(java.get("selected_count", 0) or 0)
        java_resolved = int(java.get("resolved_count", 0) or 0)
        java_rate = java_resolved / java_selected * 100.0 if java_selected else 0.0
        lines.append(
            f"{idx + 1} & {r['resolved_instances']}/500 ({rate:.1f}\\%) "
            f"& {java_selected}/128 "
            f"& {java_resolved}/{java_selected} ({java_rate:.1f}\\%) \\\\"
        )
    if summary["mean_resolved"] is not None:
        lines.append(r"\midrule")
        py_rate = summary["mean_resolved"] / 5.0
        java_mean_selected = summary.get("java_mean_selected")
        java_mean_resolved = summary.get("java_mean_resolved")
        java_rate = (
            java_mean_resolved / java_mean_selected * 100.0
            if java_mean_selected
            else 0.0
        )
        lines.append(
            f"mean & {summary['mean_resolved']:.1f}/500 ({py_rate:.1f}\\%) "
            f"& {java_mean_selected:.1f}/128 "
            f"& {java_mean_resolved:.1f}/{java_mean_selected:.1f} ({java_rate:.1f}\\%) \\\\"
        )
        lines.append(
            f"stdev & {summary['stdev_resolved_population']:.2f} & -- "
            f"& {summary.get('java_stdev_resolved_population', 0):.2f} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    (STATS_DIR / "per_run_pass1.tex").write_text("\n".join(lines) + "\n")
    print(json.dumps(summary, indent=2))


def load_java_rows() -> list[dict]:
    if not JAVA_XCHECK_PREDS_SCORE.exists():
        return []
    payload = json.loads(JAVA_XCHECK_PREDS_SCORE.read_text())
    return list(payload.get("source_runs", []))


if __name__ == "__main__":
    main()
