#!/usr/bin/env python3
"""Regenerate the RQ6 cross-track table and figure from bundled CSVs.

The script is intentionally self-contained for reviewers. It reads only
the CSV files shipped beside it and writes deterministic outputs under
``out/``. When run from the paper package, it also refreshes the
paper-facing ``stats/`` and ``figures/`` files.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CSV_DIR = ROOT / "csv"
OUT_DIR = ROOT / "out"


def read_rows(name: str) -> list[dict[str, str]]:
    with (CSV_DIR / name).open(newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(rows: list[dict[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def write_table(rows: list[dict[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by sources/rq6-cross-track/build_rq6.py",
        "% Row-level source details are in sources/rq6-cross-track/csv/cross_track_metrics.csv.",
        r"\begin{tabular}{@{}p{0.37\columnwidth}p{0.28\columnwidth}p{0.27\columnwidth}@{}}",
        r"\toprule",
        r"Signal & Python & Java \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(f"{row['signal']} & {row['python']} & {row['java']} " + r"\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    path.write_text("\n".join(lines))


def write_figure(headline: list[dict[str, str]], phase_rows: list[dict[str, str]], path: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise SystemExit(
            "matplotlib is required to regenerate the RQ6 figure. "
            "Install it with `python3 -m pip install matplotlib` or run the "
            "paper build in an environment that already has matplotlib."
        ) from exc

    path.parent.mkdir(parents=True, exist_ok=True)
    py_color = "#1f77b4"
    java_color = "#d62728"
    color_by_track = {"Python": py_color, "Java": java_color}

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(7.2, 2.55),
        gridspec_kw={"width_ratios": [0.85, 1.65]},
    )

    ax = axes[0]
    xs = list(range(len(headline)))
    rates = [float(row["rate"]) * 100 for row in headline]
    err_low = [(float(row["rate"]) - float(row["ci_lo"])) * 100 for row in headline]
    err_high = [(float(row["ci_hi"]) - float(row["rate"])) * 100 for row in headline]
    labels = [
        "Python\nSWE-bench" if row["track"] == "Python" else "Java\nMulti-SWE-bench"
        for row in headline
    ]
    colors = [color_by_track[row["track"]] for row in headline]
    ax.bar(xs, rates, color=colors, alpha=0.88, width=0.58, yerr=[err_low, err_high], capsize=4, ecolor="black")
    for idx, row in enumerate(headline):
        ax.text(
            idx,
            rates[idx] + 6.0,
            f"{rates[idx]:.2f}%\n({row['resolved']}/{row['n']})",
            ha="center",
            va="bottom",
            fontsize=7,
        )
    ax.set_xticks(xs, labels)
    ax.set_ylim(0, 92)
    ax.set_ylabel("Resolved (%)")
    ax.set_title("(a) Headline rate", loc="left", fontweight="bold", fontsize=9)
    ax.grid(axis="y", linestyle=":", alpha=0.4)
    ax.set_axisbelow(True)

    ax = axes[1]
    phase_labels = {
        "ISSUE_REPRODUCT": "Issue\nrepro",
        "TEST_SYNTHSIZE": "Test\nsynth",
        "CODE_LOCALIZE": "Code\nloc",
        "TEST_LOCALIZE": "Test\nloc",
        "CODE_FIX": "Code\nfix",
        "VERIFY_PATCH": "Verify",
        "ISSUE_CLOSE": "Close",
        "FINAL_REPORT": "Report",
    }
    phases = [phase_labels[row["phase"]] for row in phase_rows]
    py_phase = [float(row["python_share"]) * 100 for row in phase_rows]
    java_phase = [float(row["java_share"]) * 100 for row in phase_rows]
    xs = list(range(len(phases)))
    width = 0.38
    ax.bar([x - width / 2 for x in xs], py_phase, width=width, color=py_color, alpha=0.86, label="Python")
    ax.bar([x + width / 2 for x in xs], java_phase, width=width, color=java_color, alpha=0.86, label="Java")
    ax.set_xticks(xs, phases, rotation=25, ha="right", rotation_mode="anchor")
    ax.set_ylabel("Assistant messages (%)")
    ax.set_title("(b) Per-phase message share", loc="left", fontweight="bold", fontsize=9)
    ax.grid(axis="y", linestyle=":", alpha=0.4)
    ax.set_axisbelow(True)
    ax.legend(frameon=False, loc="upper right", fontsize=7)

    fig.suptitle("Kozuchi Agent + Qwen3.5-27B: Python vs. Java", fontsize=10, fontweight="bold", y=1.02)
    fig.tight_layout(pad=0.6, w_pad=1.2)
    fig.savefig(path, dpi=240, bbox_inches="tight")
    plt.close(fig)


def maybe_copy_to_paper(table_path: Path, figure_path: Path, paper_root: Path | None) -> None:
    if paper_root is None:
        return
    stats_target = paper_root / "stats" / "cross_track_summary.tex"
    figure_target = paper_root / "figures" / "cross_track_kozuchi.png"
    stats_target.parent.mkdir(parents=True, exist_ok=True)
    figure_target.parent.mkdir(parents=True, exist_ok=True)
    stats_target.write_text(table_path.read_text())
    figure_target.write_bytes(figure_path.read_bytes())
    print(f"updated {stats_target.relative_to(paper_root)}")
    print(f"updated {figure_target.relative_to(paper_root)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--paper-root",
        type=Path,
        default=None,
        help="Optional paper/final directory to refresh stats/ and figures/ outputs.",
    )
    args = parser.parse_args()

    headline = read_rows("headline.csv")
    phase_rows = read_rows("phase_distribution.csv")
    metrics = read_rows("cross_track_metrics.csv")

    out_csv = OUT_DIR / "csv" / "cross_track_summary.csv"
    out_table = OUT_DIR / "tables" / "cross_track_summary.tex"
    out_figure = OUT_DIR / "figures" / "cross_track_kozuchi.png"

    write_csv(metrics, out_csv)
    write_table(metrics, out_table)
    write_figure(headline, phase_rows, out_figure)
    maybe_copy_to_paper(out_table, out_figure, args.paper_root)

    print(f"wrote {out_csv.relative_to(ROOT)}")
    print(f"wrote {out_table.relative_to(ROOT)}")
    print(f"wrote {out_figure.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
